/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourceAttributionRouteImport } from './routes/source-attribution'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as EnforcementRouteImport } from './routes/enforcement'
import { Route as DispersionRouteImport } from './routes/dispersion'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AiAgentsRouteImport } from './routes/ai-agents'
import { Route as IndexRouteImport } from './routes/index'

const SourceAttributionRoute = SourceAttributionRouteImport.update({
  id: '/source-attribution',
  path: '/source-attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforcementRoute = EnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => rootRouteImport,
} as any)
const DispersionRoute = DispersionRouteImport.update({
  id: '/dispersion',
  path: '/dispersion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentsRoute = AiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/compare': typeof CompareRoute
  '/dispersion': typeof DispersionRoute
  '/enforcement': typeof EnforcementRoute
  '/forecasting': typeof ForecastingRoute
  '/health': typeof HealthRoute
  '/interventions': typeof InterventionsRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/response': typeof ResponseRoute
  '/source-attribution': typeof SourceAttributionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/compare': typeof CompareRoute
  '/dispersion': typeof DispersionRoute
  '/enforcement': typeof EnforcementRoute
  '/forecasting': typeof ForecastingRoute
  '/health': typeof HealthRoute
  '/interventions': typeof InterventionsRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/response': typeof ResponseRoute
  '/source-attribution': typeof SourceAttributionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agents': typeof AiAgentsRoute
  '/compare': typeof CompareRoute
  '/dispersion': typeof DispersionRoute
  '/enforcement': typeof EnforcementRoute
  '/forecasting': typeof ForecastingRoute
  '/health': typeof HealthRoute
  '/interventions': typeof InterventionsRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/response': typeof ResponseRoute
  '/source-attribution': typeof SourceAttributionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents'
    | '/compare'
    | '/dispersion'
    | '/enforcement'
    | '/forecasting'
    | '/health'
    | '/interventions'
    | '/knowledge-graph'
    | '/response'
    | '/source-attribution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents'
    | '/compare'
    | '/dispersion'
    | '/enforcement'
    | '/forecasting'
    | '/health'
    | '/interventions'
    | '/knowledge-graph'
    | '/response'
    | '/source-attribution'
  id:
    | '__root__'
    | '/'
    | '/ai-agents'
    | '/compare'
    | '/dispersion'
    | '/enforcement'
    | '/forecasting'
    | '/health'
    | '/interventions'
    | '/knowledge-graph'
    | '/response'
    | '/source-attribution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentsRoute: typeof AiAgentsRoute
  CompareRoute: typeof CompareRoute
  DispersionRoute: typeof DispersionRoute
  EnforcementRoute: typeof EnforcementRoute
  ForecastingRoute: typeof ForecastingRoute
  HealthRoute: typeof HealthRoute
  InterventionsRoute: typeof InterventionsRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  ResponseRoute: typeof ResponseRoute
  SourceAttributionRoute: typeof SourceAttributionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/source-attribution': {
      id: '/source-attribution'
      path: '/source-attribution'
      fullPath: '/source-attribution'
      preLoaderRoute: typeof SourceAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforcement': {
      id: '/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof EnforcementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispersion': {
      id: '/dispersion'
      path: '/dispersion'
      fullPath: '/dispersion'
      preLoaderRoute: typeof DispersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agents': {
      id: '/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentsRoute: AiAgentsRoute,
  CompareRoute: CompareRoute,
  DispersionRoute: DispersionRoute,
  EnforcementRoute: EnforcementRoute,
  ForecastingRoute: ForecastingRoute,
  HealthRoute: HealthRoute,
  InterventionsRoute: InterventionsRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  ResponseRoute: ResponseRoute,
  SourceAttributionRoute: SourceAttributionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
